version: "3.4"

services:
  deliveggie-gateway-api:
    image: deliveggie-gateway-api
    container_name: "deliveggie-gateway-api"
    build:
      context: .
      dockerfile: src/Gateway/DeliVeggie.GatewayAPI/Dockerfile
    environment:
      ConnectionStrings__RabbitMqConnectionString: host=localhost:5672;publisherConfirms=true;timeout=10
    ports:
      - 5062:80
    depends_on:
      - rabbitmq
    networks:
      - deliveggie-network
  deliveggie-data-service:
    image: deliveggie-data-service
    container_name: "deliveggie-data-service"
    build:
      context: .
      dockerfile: src/Services/DeliVeggie.Data.Product/Dockerfile
    environment:
      ConnectionStrings__MongoConnectionString: mongodb://localhost:27017/deli-veggie
      ConnectionStrings__RabbitMqConnectionString: host=localhost:5672;publisherConfirms=true;timeout=10
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - deliveggie-network
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "deliveggie-products-rabbitmq"
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    # environment:
    #   RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
    #   RABBITMQ_DEFAULT_USER: deliveggie
    #   RABBITMQ_DEFAULT_PASS: deliveggie
    expose:
      - 5672
      - 15672
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - deliveggie-network
  mongo:
    image: mongo
    restart: always
    container_name: "deliveggie-mongodb"
    ports:
      - 27017:27017
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: deliveggie
    # MONGO_INITDB_ROOT_PASSWORD: deliveggie
    networks:
      - deliveggie-network
  mongo-express:
    image: mongo-express
    container_name: "deliveggie-mongodb-ui"
    restart: always
    ports:
      - 27027:8081
    # environment:
    # ME_CONFIG_MONGODB_ADMINUSERNAME: deliveggie
    # ME_CONFIG_MONGODB_ADMINPASSWORD: deliveggie
    networks:
      - deliveggie-network

networks:
  deliveggie-network:
    driver: bridge
